"""Restructure video summaries

Revision ID: 0d0d383466eb
Revises: b9b0104cbc08
Create Date: 2024-10-10 16:56:09.652066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0d383466eb'
down_revision = 'b9b0104cbc08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_summary', schema=None) as batch_op:
        batch_op.drop_constraint('uq_video_user', type_='unique')
        batch_op.create_unique_constraint(None, ['video_id'])
        batch_op.drop_constraint('video_summary_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('video_summary_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('uq_video_user', ['video_id', 'user_id'])

    # ### end Alembic commands ###
