"""Add ChannelReport and UserReportAccess models

Revision ID: 4244d80f668c
Revises: 348a873f92b8
Create Date: 2024-09-18 16:34:10.577263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4244d80f668c'
down_revision = '348a873f92b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_channel_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_report', schema=None) as batch_op:
        batch_op.drop_column('raw_channel_data')

    # ### end Alembic commands ###
