"""Add watch history analysis table

Revision ID: 4818ea06ec5c
Revises: 
Create Date: 2024-11-02 14:30:23.722898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4818ea06ec5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_history_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_data', sa.Text(), nullable=False),
    sa.Column('raw_history_data', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_history_analysis')
    # ### end Alembic commands ###
