"""Remove content_category_confidence from ChannelReport model

Revision ID: 74e103962a9e
Revises: 9109b4997e0b
Create Date: 2024-09-25 15:03:56.964047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e103962a9e'
down_revision = '9109b4997e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_report', schema=None) as batch_op:
        batch_op.drop_column('content_category_confidence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_category_confidence', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
