"""Update VideoSummary model

Revision ID: 7b96794ec948
Revises: 74e103962a9e
Create Date: 2024-09-26 14:15:44.773199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b96794ec948'
down_revision = '74e103962a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_summary', schema=None) as batch_op:
        batch_op.drop_constraint('video_summary_video_id_key', type_='unique')
        batch_op.create_unique_constraint('uq_video_user', ['video_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_summary', schema=None) as batch_op:
        batch_op.drop_constraint('uq_video_user', type_='unique')
        batch_op.create_unique_constraint('video_summary_video_id_key', ['video_id'])

    # ### end Alembic commands ###
