"""Add nullable raw_channel_data to Report model

Revision ID: b1268ba32163
Revises: fc0d4f606892
Create Date: 2024-09-15 16:41:48.296259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1268ba32163'
down_revision = 'fc0d4f606892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_channel_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('raw_channel_data')

    # ### end Alembic commands ###
